# Generated by Django 3.2.14 on 2022-07-19 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=40, unique=True)),
                ('dob', models.DateField()),
                ('address', models.TextField(max_length=256)),
                ('photo', models.FileField(upload_to='photos/')),
                ('age', models.IntegerField()),
                ('contact', models.BigIntegerField()),
            ],
            options={
                'db_table': 'Customer_Master',
            },
        ),
    ]
