# Generated by Django 3.2.14 on 2022-07-26 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m2m', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='Cust',
            field=models.ManyToManyField(related_name='addresses', to='m2m.Customer'),
        ),
    ]
